// Static Content Data
// Arabic content
const arabicContent = {
  headline: "تجربة شتوية دافئة في مطعم حلاوة",
  subheadline: "بوفيه غداء و بوفيه عشاء كل خميس و جمعة و سبت",
  heroLocation: "عمان - خلدا",
  cta: "جرب أجواء حلاوة الدافئة",
  benefitsSubtitle: "بتدور على فعالية شتوية تجمع العائلة وتقدّم تجربة طعام متكاملة في أجواء دافئة؟",
  benefitsIntro: "بتجربتنا رح تستمتعوا بـ:",
  benefit1: "مأكولات عربية",
  benefit2: "حلويات عربية",
  benefit3: "حلويات عالمية",
  benefit4: "مشروبات ساخنة",
  benefit5: "مشروبات باردة",
  benefit6: "أجواء شتوية عائلية",
  reviewsTitle: "شو قالوا ضيوفنا عن التجربة؟",
  reviewQuestion1: "ما رأيك في الأطباق الرئيسية؟",
  reviewCustomer1: "أحمد محمد",
  reviewAnswer1: "الأطباق كانت لذيذة والنكهات الأصلية للشرق الأوسط واضحة في كل قضمة. خاصة المندي والكبسة كانت استثنائية!",
  reviewQuestion2: "كيف كانت الأجواء العائلية؟",
  reviewCustomer2: "فاطمة أحمد",
  reviewAnswer2: "الأجواء كانت دافئة ومريحة جداً، مناسبة للعائلات. الأطفال استمتعوا بالألعاب والأجواء الشتوية الجميلة، والكبار استمتعوا بالمحادثات الودية.",
  reviewQuestion3: "ما رأيك في الحلويات المقدمة؟",
  reviewCustomer3: "محمد علي",
  reviewAnswer3: "الحلويات كانت رائعة! من الكنافة إلى البقلاوة، كل شيء كان طازجاً ولذيذاً. خاصة الكنافة بالكريمة كانت لا تقاوم!",
  reviewQuestion4: "هل تنصح بزيارة المطعم في الشتاء؟",
  reviewCustomer4: "سارة حسن",
  reviewAnswer4: "بالتأكيد! الجلوس الداخلي دافئ والديكور الشتوي جميل جداً. بوفيه الشتاء هي تجربة لا تفوت، خاصة مع الأسعار المعقولة والخدمة الممتازة.",
  reviewQuestion5: "كيف وجدت جودة الخدمة؟",
  reviewCustomer5: "عمر خالد",
  reviewAnswer5: "الخدمة كانت ممتازة والموظفين كانوا ودودين جداً. كل شيء نحتاجه كان متوفراً بسرعة والنظافة كانت في أعلى المستويات.",
  reviewQuestion6: "ما رأيك في المشروبات المقدمة؟",
  reviewCustomer6: "لينا محمود",
  reviewAnswer6: "المشروبات كانت متنوعة ومناسبة لموسم الشتاء. الشاي والقهوة كانتا ساخنتين ولذيذتين، والعصائر الطازجة كانت منعشة جداً.",
  lunchTitle: "بوفيه الغداء – 3:00 مساءً",
  dinnerTitle: "بوفيه العشاء – 8:00 مساءً",
  lunchArabicCuisine: "مأكولات عربية",
  lunchArabicDesserts: "حلويات عربية",
  lunchInternationalDesserts: "حلويات عالمية",
  lunchHotDrinks: "مشروبات ساخنة",
  lunchColdDrinks: "مشروبات باردة",
  dinnerArabicCuisine: "مأكولات عربية",
  dinnerArabicDesserts: "حلويات عربية",
  dinnerInternationalDesserts: "حلويات عالمية",
  dinnerHotDrinks: "مشروبات ساخنة",
  dinnerColdDrinks: "مشروبات باردة",
  kidsTitle: "🎨 اضغط لاكتشاف ما أعددناه لأطفالنا",
  kidsActivity1: "ركن الفنون والحرف",
  kidsActivity2: "ألعاب تفاعلية خفيفة",
  kidsActivity3: "قصص وحكايات ممتعة",
  eventTitle: "تفاصيل الفعالية العائلية",
  eventPrice: "سعر المقعد: <strong> 20 دينار</strong>",
  eventDays: "الأيام: <strong>كل خميس، جمعة، وسبت</strong>",
  eventPeriod: "فترة الفعالية: <strong>من 20/1 ولمدة شهر</strong>",
  eventTimesTitle: "أوقات البوفيه:",
  lunchTime: "الغداء: <strong>3:00 مساءً</strong>",
  dinnerTime: "العشاء: <strong>8:00 مساءً</strong>",
  eventDuration: "مدة الفعالية: <strong>3 ساعات</strong>",
  eventSeats: " مقاعد محدودة: <strong>200 مقعد</strong>",
  bookingTitle: "احجز مكانك في الفعالية",
  bookingBtn: "احجز الآن",
  fullNameLabel: "الاسم الكامل *",
  numPeopleLabel: "عدد الأشخاص *",
  mealTypeLabel: "نوع البوفيه *",
  mealTypeDefault: "اختر نوع البوفيه",
  mealTypeLunch: "غداء",
  mealTypeDinner: "عشاء",
  bookingDateLabel: "تاريخ الحجز *",
  dateInfo: "الفعالية متاحة في أيام الخميس والجمعة والسبت من 20 يناير إلى 20 فبراير",
  notesLabel: "ملاحظات إضافية",
  popupTitle: "شكراً لك!",
  popupMessage: "تم تأكيد الحجز بنجاح. شكرًا لاختياركم فعاليتنا.",
  policiesTitle: "السياسات والشروط",
  cancellationPolicy: "سياسة الإلغاء: يمكن إلغاء الحجز حتى 24 ساعة قبل موعد الفعالية مع استرداد كامل للمبلغ.",
  returnPolicy: "سياسة الإرجاع: لا يمكن إرجاع التذاكر بعد حضور الفعالية.",
  supportTitle: "الدعم والمساعدة",
  whatsappLink: "دعم واتساب",
  whatsappSupport: "دعم واتساب",
  shareEventTitle: "مشاركة الفعالية",
  shareEventText: "مشاركة",
  shareTitle: "مشاركة الفعالية",
  whatsappShareText: "واتساب",
  instagramShareText: "إنستغرام",
  youtubeShareText: "يوتيوب",
  copyrightText: "2026 مطعم حلاوة. جميع الحقوق محفوظة.",
  locationText: "عمان-خلدا",
};

// English content
const englishContent = {
  headline: "Warm Winter Experience at Halaweh Restaurant",
  subheadline: "Lunch Buffet & Dinner Buffet Every Thursday, Friday & Saturday",
  heroLocation: "Amman - Khalda",
  cta: "Experience Halaweh's Warm Atmosphere",
  benefitsSubtitle: "Looking for a winter event that brings the family together and offers a complete food experience in a warm atmosphere?",
  benefitsIntro: "With our experience, you'll enjoy:",
  benefit1: "Arabic Cuisine",
  benefit2: "Arabic Desserts",
  benefit3: "International Desserts",
  benefit4: "Hot Drinks",
  benefit5: "Cold Drinks",
  benefit6: "Family Winter Atmosphere",
  reviewsTitle: "What Did Our Guests Say About The Experience?",
  reviewQuestion1: "What did you think of the main dishes?",
  reviewCustomer1: "Ahmed Mohamed",
  reviewAnswer1: "The dishes were absolutely delicious and the authentic flavors of the Middle East were evident in every bite. Especially the Mandi and Kabsa were exceptional!",
  reviewQuestion2: "How was the family atmosphere?",
  reviewCustomer2: "Fatima Ahmed",
  reviewAnswer2: "The atmosphere was very warm and comfortable, perfect for families. The children enjoyed the games and beautiful winter atmosphere, and the adults enjoyed the friendly conversations.",
  reviewQuestion3: "What did you think of the desserts served?",
  reviewCustomer3: "Mohamed Ali",
  reviewAnswer3: "The desserts were amazing! From Knafeh to Baklava, everything was fresh and delicious. Especially the Knafeh with cream was irresistible!",
  reviewQuestion4: "Do you recommend visiting the restaurant in winter?",
  reviewCustomer4: "Sarah Hassan",
  reviewAnswer4: "Absolutely! The indoor seating is warm and the winter decor is very beautiful. The winter buffet is an experience not to be missed, especially with reasonable prices and excellent service.",
  reviewQuestion5: "How did you find the quality of service?",
  reviewCustomer5: "Omar Khalid",
  reviewAnswer5: "The service was excellent and the staff were very friendly. Everything we needed was available quickly and cleanliness was at the highest levels.",
  reviewQuestion6: "What did you think of the drinks served?",
  reviewCustomer6: "Lina Mahmoud",
  reviewAnswer6: "The drinks were diverse and suitable for the winter season. The tea and coffee were hot and delicious, and the fresh juices were very refreshing.",
  lunchTitle: "Lunch Buffet – 3:00 PM",
  dinnerTitle: "Dinner Buffet – 8:00 PM",
  lunchArabicCuisine: "Arabic Cuisine",
  lunchArabicDesserts: "Arabic Desserts",
  lunchInternationalDesserts: "International Desserts",
  lunchHotDrinks: "Hot Drinks",
  lunchColdDrinks: "Cold Drinks",
  dinnerArabicCuisine: "Arabic Cuisine",
  dinnerArabicDesserts: "Arabic Desserts",
  dinnerInternationalDesserts: "International Desserts",
  dinnerHotDrinks: "Hot Drinks",
  dinnerColdDrinks: "Cold Drinks",
  kidsTitle: "🎨 Click to Discover What We Have Prepared for Our Children",
  kidsActivity1: "Art and Crafts Corner",
  kidsActivity2: "Interactive Light Games",
  kidsActivity3: "Fun Stories and Tales",
  eventTitle: "Family Event Details",
  eventPrice: "Seat Price: 20 Dinars",
  eventDays: "Days: Every Thursday, Friday, and Saturday",
  eventPeriod: "Event Period: From 1/20 for one month",
  eventTimesTitle: "Buffet Times:",
  lunchTime: "Lunch: 3:00 PM",
  dinnerTime: "Dinner: 8:00 PM",
  eventDuration: "Event Duration: 3 hours",
  eventSeats: " Limited Seats: 200 seats",
  bookingTitle: "Book Your Place at Event",
  bookingBtn: "Book Now",
  fullNameLabel: "Full Name *",
  numPeopleLabel: "Number of People *",
  mealTypeLabel: "Buffet Type *",
  mealTypeDefault: "Select Buffet Type",
  mealTypeLunch: "Lunch",
  mealTypeDinner: "Dinner",
  bookingDateLabel: "Booking Date *",
  dateInfo: "The event is available on Thursdays, Fridays, and Saturdays from January 20 to February 20",
  notesLabel: "Additional Notes",
  popupTitle: "Thank You!",
  popupMessage: "Booking confirmed successfully. Thank you for choosing our event.",
  policiesTitle: "Policies & Terms",
  cancellationPolicy: "Cancellation Policy: Bookings can be cancelled up to 24 hours before the event with full refund.",
  returnPolicy: "Return Policy: Tickets cannot be returned after attending the event.",
  supportTitle: "Support & Help",
  whatsappLink: "WhatsApp Support",
  whatsappSupport: "WhatsApp Support",
  shareEventTitle: "Share Event",
  shareEventText: "Share",
  shareTitle: "Share Event",
  whatsappShareText: "WhatsApp",
  instagramShareText: "Instagram",
  youtubeShareText: "YouTube",
  copyrightText: "2026 Halaweh Restaurant. All rights reserved.",
  locationText: "Amman-Khalda",
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    arabicContent,
    englishContent
  };
}